[package]
name = "asm-lsp"
version = "0.2.0"
authors = ["Nikos Koukis <nickkouk@gmail.com>"]
edition = "2018"

description = "Assembly Language Server"

documentation = "https://github.com/bergercookie/asm-lsp"
homepage = "https://github.com/bergercookie/asm-lsp"
repository = "https://github.com/bergercookie/asm-lsp"

readme = "README.md"

keywords = ["assembly", "productivity", "x86", "arm", "tooling"]
publish = true
exclude = ["samples/*",
           "demo/*", ]
license = "BSD-2-Clause"

[lib]
name = "asm_lsp"
path = "src/lib.rs"
[[bin]]
name = "asm-lsp"
path = "src/bin/main.rs"

[badges]

cirrus-ci = { repository = "asm-lsp", branch = "master" }


[dependencies]
anyhow = "1.0.31"
flexi_logger = "0.15.7" # write to stderr instead of stdout
log = {version = "0.4.8"}
lsp-server = "0.3.3"
lsp-types = "0.77.0"
quick-xml = "0.18.1"
regex = "1.3.9"
reqwest = {version = "0.10.6", features = ["blocking"]}
strum = "0.18.0"
strum_macros = "0.18.0"
serde_json = "1.0.56"
serde = "1.0.114"

# [dev-dependencies]
