[package]
name = "look-asm"
version = "0.1.0"
authors = ["Nikos Koukis <nickkouk@gmail.com>"]
edition = "2018"

description = "Lookup assembly opcodes without leaving your terminal"

documentation = "https://github.com/bergercookie/look-asm"
homepage = "https://github.com/bergercookie/look-asm"
repository = "https://github.com/bergercookie/look-asm"

readme = "README.md"

keywords = ["assembly", "productivity", "x86", "arm", "tooling"]
publish = true
exclude = [ ]
license = "BSD-2-Clause"

[badges]

cirrus-ci = { repository = "look-asm", branch = "master" }


[dependencies]
anyhow = "1.0.31"
flexi_logger = "0.15.7" # write to stderr instead of stdout
log = {version = "0.4.8"}
lsp-server = "0.3.3"
lsp-types = "0.77.0"
quick-xml = "0.18.1"
regex = "1.3.9"
reqwest = {version = "0.10.6", features = ["blocking"]}
strum = "0.18.0"
strum_macros = "0.18.0"
thiserror = "1.0.20"
serde_json = "1.0.56"
serde = "1.0.114"

# [dev-dependencies]
