[package]
name = "look-asm"
version = "0.1.0"
authors = ["Nikos Koukis <nickkouk@gmail.com>"]
edition = "2018"

description = "Lookup assembly opcodes without leaving your terminal"

documentation = "https://github.com/bergercookie/look-asm"
homepage = "https://github.com/bergercookie/look-asm"
repository = "https://github.com/bergercookie/look-asm"

readme = "README.md"

keywords = ["assembly", "productivity", "x86", "arm", "tooling"]
publish = true
exclude = [ ]
license = "BSD-2-Clause"

[badges]

cirrus-ci = { repository = "look-asm", branch = "master" }


[dependencies]
anyhow = "1.0.31"
quick-xml = "0.18.1"
log = {version = "0.4.8"}
env_logger = "0.7.1"
reqwest = {version = "0.10.6", features = ["blocking"]}
regex = "1.3.9"
strum = "0.18.0"
strum_macros = "0.18.0"
thiserror = "1.0.20"

# [dev-dependencies]
