name: Publish Crate

on:
  workflow_dispatch:
  push:
    # Pattern matched against refs/tags
    tags:
      - "*"

jobs:
  publish:
    name: Publish Crate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.0
        name: Run pre-commit hooks

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          ignore-unpublished-changes: true
